services:
  php:
    build:
      context: ./docker/php
    container_name: ${DOCKER_PREFIX}_php
    volumes:
      - .:/var/www/html:delegated
    working_dir: /var/www/html
    networks:
      - lightning_net

  nginx:
    image: nginx:latest
    container_name: ${DOCKER_PREFIX}_nginx
    volumes:
      - .:/var/www/html:delegated
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/nginx/sites:/etc/nginx/conf.d:ro
      - ./docker/nginx/ssl:/etc/nginx/ssl:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - php
    networks:
      - lightning_net

  db:
    image: mariadb:latest
    container_name: ${DOCKER_PREFIX}_db
    volumes:
      - db_data_dev:/var/lib/mysql
    env_file:
      - .env
    ports:
      - "3307:3306"
    networks:
      - lightning_net

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ${DOCKER_PREFIX}_phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
    depends_on:
      - db
    networks:
      - lightning_net

  nuxt:
    image: node:18-alpine
    container_name: ${DOCKER_PREFIX}_nuxt
    working_dir: /app
    command: sh -c "npm install && CHOKIDAR_USEPOLLING=true npm run dev"
    volumes:
      - ./templates/${SITE_TEMPLATE}:/app:delegated
      - nuxt_node_modules:/app/node_modules
    ports:
      - "3000:3000"
      - "24678:24678"
    networks:
      - lightning_net

  nuxt_admin:
    image: node:18-alpine
    container_name: ${DOCKER_PREFIX}_nuxt_admin
    working_dir: /app
    command: sh -c "npm install && CHOKIDAR_USEPOLLING=true npm run dev"
    volumes:
      - ./templates/admin:/app:delegated
      - nuxt_admin_node_modules:/app/node_modules
    ports:
      - "3001:3001"
      - "24679:24679"
    networks:
      - lightning_net

volumes:
  db_data_dev:
  nuxt_node_modules:
  nuxt_admin_node_modules:

networks:
  lightning_net:
    driver: bridge
